Wallet in Diario
[Region: europe-west4]
==============
Using Nixpacks
==============

context: x5zq-KV1u
╔═════════════════════ Nixpacks v1.38.0 ═════════════════════╗
║ setup      │ nodejs_18, npm-9_x                            ║
║────────────────────────────────────────────────────────────║
║ caddy      │ pkgs: caddy                                   ║
║            │ cmds: caddy fmt --overwrite /assets/Caddyfile ║
║────────────────────────────────────────────────────────────║
║ install    │ npm ci                                        ║
║────────────────────────────────────────────────────────────║
║ build      │ npm run build                                 ║
║────────────────────────────────────────────────────────────║
║ start      │ npm run start                                 ║
╚════════════════════════════════════════════════════════════╝

internal
load build definition from Dockerfile
0ms

internal
load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1745885067
349ms

internal
load .dockerignore
0ms

internal
load build context
0ms

stage-0
FROM ghcr.io/railwayapp/nixpacks:ubuntu-1745885067@sha256:d45c89d80e13d7ad0fd555b5130f22a866d9dd10e861f589932303ef2314c7de
10ms

stage-0
WORKDIR /app/ cached
0ms

stage-0
COPY .nixpacks/nixpkgs-ba913eda2df8eb72147259189d55932012df6301.nix .nixpacks/nixpkgs-ba913eda2df8eb72147259189d55932012df6301.nix
29ms

stage-0
RUN nix-env -if .nixpacks/nixpkgs-ba913eda2df8eb72147259189d55932012df6301.nix && nix-collect-garbage -d
35s
36 store paths deleted, 243.63 MiB freed

stage-0
COPY .nixpacks/nixpkgs-ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7.nix .nixpacks/nixpkgs-ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7.nix
54ms

stage-0
RUN nix-env -if .nixpacks/nixpkgs-ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7.nix && nix-collect-garbage -d
44s
61 store paths deleted, 559.56 MiB freed

stage-0
COPY .nixpacks/assets /assets/
104ms

stage-0
COPY . /app/.
58ms

stage-0
RUN  caddy fmt --overwrite /assets/Caddyfile
220ms

stage-0
COPY . /app/.
76ms

stage-0
RUN npm ci
4s
Run `npm audit` for details.

stage-0
COPY . /app/.
125ms

stage-0
RUN npm run build
7s
npm warn config production Use `--omit=dev` instead.
> valeria-landing@1.0.0 build
> tsc && vite build
src/constants/calendly.ts(34,59): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

Dockerfile:30
-------------------
28 |     # build phase
29 |     COPY . /app/.
30 | >>> RUN --mount=type=cache,id=s/b29ea8d5-6470-45c0-9c75-922e9f03e5ae-node_modules/cache,target=/app/node_modules/.cache npm run build
31 |
32 |
-------------------
ERROR: failed to build: failed to solve: process "/bin/bash -ol pipefail -c npm run build" did not complete successfully: exit code: 2
Error: Docker build failed